name: "pbuf-setup"
description: "Install pbuf-cli for use in other jobs"
author: "pbuf.io"

branding:
  color: purple
  icon: power

inputs:
  version:
    description: The version of the CLI
    required: false
    default: 'v0.3.1'
  pbuf_token:
    description: The API token to use with PBUF registry.
    required: false

runs:
  using: node20
  main: dist/index.js
